# Generated by Django 3.1 on 2020-08-30 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_auto_20200806_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='title',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='places.place'),
        ),
    ]
