# Generated by Django 3.1 on 2020-09-01 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_image_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='image',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
