# Generated by Django 3.1 on 2020-09-01 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_auto_20200901_1731'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='lat',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='lng',
            new_name='longitude',
        ),
    ]
