# Generated by Django 3.1 on 2020-09-07 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_auto_20200901_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='places.place'),
        ),
    ]
